---
- hosts: vagrant
  sudo: true
  vars:
    # [OPTIONAL] GitHub OAuth token to extend API rate limit
    # How to generate it: https://github.com/blog/1509-personal-api-tokens
    - github_oauth_token: "23330eb990f07464b590b029e33cc8a5233aadd8"
  vars_files:
    - defaults/variables.yml

  roles:
    - initial
    - common
    - nginx
    - php
    - composer
    - phpredis
    - redis
    - memcached
    - sqlite
    - mysql
    - postgresql
    - mongodb
    - phpmongo
    - phpmyadmin
    - adminer
    - yii-advanced-project
    - project-db
    #- sakila-db
